glib: android/config/config.h: Switch to `USE_STATFS` from `USE_STATVFS`
external/glib/gio/glocalfile.c:1098:12: error: call to undeclared function 'get_fs_type'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1098 |   fstype = get_fs_type (statfs_buffer.f_type);
      |            ^
external/glib/gio/glocalfile.c:1098:39: error: no member named 'f_type' in 'struct statvfs'
 1098 |   fstype = get_fs_type (statfs_buffer.f_type);
      |                         ~~~~~~~~~~~~~ ^
2 errors generated.